### ISSUE TITLE
Googletest bug

### ISSUE THREAD

**Issue by olaszsoma** [gergopokol/Runafluid#1]
The test.sh script has been set to bash interpreter, and couldn't be run on tcsh. The Makefile has created a test_imas.bin file, whereas the test.sh script tried to run test.bin regardless of the environment, which has not been created.

**Comment by gergopokol** [comment]
Partly the same as https://github.com/gergopokol/Runin/issues/1 .

**Comment by olaszsoma** [comment]
Makefile has been modified to create test.bin files in both ITM and IMAS environments.

**Comment by olaszsoma** [comment]
Makefile problem has been resolved, the test is still to be done. The googletest for Runafluid is unfinished, it has to be done. A separate project will be created for unit testing the Runafluid and Runin calculations.

**Comment by olaszsoma** [comment]
test.sh message for the missing GTEST variable is not up-to-date, this was fixed.
