### ISSUE TITLE
Find HDF5 package in CMakeLists.txt

### ISSUE THREAD

**Issue by olaszsoma** [gergopokol/Runafluid#107]
Two lines are commented in the [CMakelists.txt](https://github.com/osrep/Runafluid/blob/master/CMakeLists.txt#L13) file looking for HDF5 packages. The reason for commenting should be reviewed and the line maybe removed.

**Comment by pordaniel01** [comment]
These lines can be removed, as the commands
```
execute_process(COMMAND eval-pkg-config --cflags ual-cpp-gnu --cflags hdf5-cpp-gnu --cflags itmconstants --cflags xmllib-$ENV{ITM_GCC_OBJECTCODE}
			OUTPUT_VARIABLE cxx_flags)
```
and 
```
execute_process(COMMAND eval-pkg-config --libs ual-cpp-gnu hdf5-cpp-gnu xmllib-$ENV{ITM_GCC_OBJECTCODE}
			OUTPUT_VARIABLE linker_flags)
```
Adds HDF5 flags to the linker and compiler. However this is system specific, as these lines only work on Gateway. 
The commented find_package(HDF5), in theory finds and adds to the linker and compiler the HDF5 library, as [this page](https://cmake.org/cmake/help/latest/module/FindHDF5.html) describes it. 
We should decide which method should be used, and both should be tested on all systems we intend to run the code on.

**Comment by olaszsoma** [comment]
Lines removed, if necessary, this issue can be revisited.
