### ISSUE TITLE
Runaway distribution at center of plasma

### ISSUE THREAD

**Issue by olaszsoma** [gergopokol/Runafluid#15]
The runaway population cannot be calculated at the center of the plasma, the runaway_control function gives NaN value at that location. This should not be the case, the reason for this behavior has to be found and fixed.

**Comment by gergopokol** [comment]
We could narrow down the source of the problem by trying to reproduce with different runaway generation modells, including the choice to use none.

**Comment by olaszsoma** [comment]
After printing the value of the calculated rundensity this issue does not seem valid. The calculation ran fine with the electric field below and above the critical field as well.
