### ISSUE TITLE
modules vs. switch integers

### ISSUE THREAD

**Issue by matyasaradi** [gergopokol/Runafluid#17]
Code cleaning is needed due to the parallel work of `modules m` structure and switch integers: `runafluid_switch` (runafluid*, control.* ), `modulevar_avalanche` (avalance.* ), `formula_id` (dreicer.* )
see: 929bbddd8e94b2c07feb6c086dc705871846425c and d2f1b068e17bff49f0b99b8cc71ae0255e9f2d28
The `modules` structure is prefered, but with a more readable structure and variable name (e.g. `modules m` ➜ `module_struct modules`)

**Comment by olaszsoma** [comment]
The change to modules from switches is not working in IMAS environment. The coding has to be revised and corrected.

**Comment by olaszsoma** [comment]
The [allocation](https://github.com/osrep/Runafluid/blob/master/runafluid_imas.cpp#L210) of the rate values for each rho index is causing the Kepler workflow to crash. I am not sure why this might be, as the same piece of code is working in ITM environment. More testing required.

**Comment by olaszsoma** [comment]
The allocation problem has been found in the ITM environment as well, the array elements have to be called using () brackets instead of [] brackets.

**Comment by olaszsoma** [comment]
This issue is connected to issue #21, it will be handled there.
