### ISSUE TITLE
Runafluid output distribution CPO run number

### ISSUE THREAD

**Issue by olaszsoma** [gergopokol/Runafluid#32]
We have to figure out if the current implementation of the Runaway test workflow is the correct way to do it. Namely, whether Runafluid writes the output distribution in the correct way. Discuss with Dmitriy.

**Comment by olaszsoma** [comment]
During the execution of a workflow any data should be written to the run given by the variable run_work (or something like that). This data (or part of it) will be written to run_out by a UALputslice actor. Any other actor should write to run_work.

**Comment by gergopokol** [comment]
> 
> 
> During the execution of a workflow any data should be written to the run given by the variable run_work (or something like that). This data (or part of it) will be written to run_out by a UALputslice actor. Any other actor should write to run_work.

This info is from Jorge, and we are not sure if this procedure is followed by Runafluid.

**Comment by olaszsoma** [comment]
It seems that Runafluid does not write to any run or shot numbers, it just creates a standalone distribution CPO which is merged with other distributions later in the workflow. This issue should be discussed with Thomas or Dmitriy.

**Comment by olaszsoma** [comment]
This issue is relevant for the workflow management. The workflows are version controlled [here](https://gforge6.eufus.eu/gf/project/keplerworkflows/scmsvn/?action=browse&path=%2Ftrunk%2F4.10b%2Frunaways%2F). This issue can be closed.
