### ISSUE TITLE
Electric field writing to profiles is zero when B is zero

### ISSUE THREAD

**Issue by olaszsoma** [gergopokol/Runafluid#35]
The electric field [writing ](https://github.com/osrep/Runafluid/blob/development/cpo_utils.cpp#L252)to the cell structure includes the magnetic field for some reason. This modifies the value of the electric field, and if the magnetic field is zero, the electric field will be zero as well. Have a look into this.

**Comment by olaszsoma** [comment]
The parallelization of electric field to the toroidal magnetic field is a bug, the CPO electric field used is already the parallel field.  This has to be fixed, maybe a check of the CPO input field (check if it is the parallel field or not) can be implemented.

**Comment by olaszsoma** [comment]
The allocation of parallel electric field to the profiles has been fixed with the parallelization of the electric field to the magnetic field being removed. The modifications have been tested on ITM environment (not on IMAS), so a merge can be done.

**Comment by gergopokol** [comment]
How do others handle this E_par os E_tor question? (LUKE, Chalmers codes...)

**Comment by olaszsoma** [comment]
The parallel electric field in CPOs is a flux surface average (see [link)](https://portal.eufus.eu/documentation/ITM/imports/isip/public/data_structure/4.10b.10/coreprof_xsd.html#coreprof_profiles1d). It is calculated as: "Parallel electric field = average(E.B) / B0, where B0 = coreprof/toroid_field/b0 [V.m^-1]."

**Comment by gergopokol** [comment]
Ok, the E_par is to be used, for sure.

**Comment by olaszsoma** [comment]
Modifications merged, the issue can be closed.
