### ISSUE TITLE
Calculation of Z_eff from impurities should be added

### ISSUE THREAD

**Issue by olaszsoma** [gergopokol/Runafluid#50]
The calculation of the effective charge is done in [Runin](https://github.com/osrep/Runin/blob/master/cpo_utils.cpp#L80) using the impurity and main ion content of the plasma. [Runafluid](https://github.com/osrep/Runafluid/blob/master/cpo_utils.cpp#L281) uses the corperof.zeff CPO as the effective charge. For consistency, the same method should be used for obtaining this. Since in Runafluid 2.0, the impurities will be needed for the improved analytical formulas, the method used in Runin will be implemented to Runafluid as well.

**Comment by pordaniel01** [comment]
This may be in Runaphys now.

**Comment by gergopokol** [comment]
This should be implemented in Runaway Fluid, as it concerns the inputs.
