### ISSUE TITLE
HDF5 output file

### ISSUE THREAD

**Issue by gergopokol** [gergopokol/Runafluid#51]
Could consider removing the option to set the path and name for the HDF5 output file, and automatically put the output to the database hdf5 folder sitting beside the mdsplus folder with the same name as the mdsplus output file just with an additional _runafluid tag.

This is related to #47

**Comment by olaszsoma** [comment]
Check if this is possible.

**Comment by olaszsoma** [comment]
The default location was changed, the output file location will be changed when the hdf5 output will be changed to boolean (see #47).

**Comment by olaszsoma** [comment]
The [annotation](https://github.com/osrep/Runafluid/blob/Update_codeparams/xml/runafluid.xsd#L208) in the code parameters file caused some problems, this was changed. The variable $HDF5_BASE was not defined in the Kepler, this raised an error message. The change removed the error message which appeared when the actor was inserted to the Kepler canvas.
