### ISSUE TITLE
Remove Runaway test workflow from Runafluid repo

### ISSUE THREAD

**Issue by gergopokol** [gergopokol/Runafluid#53]
Runafluid repository is to store the Runaway Fluid actor. All Kepler workflows are to be stored at other locations. The Runaway test workflow includes all runaway actors and it can only be run in the proper environment. It will, thus, be moved into the kepler_workflows SV repository at GForge.

**Comment by olaszsoma** [comment]
The workflows have been moved to [kepler_workflows repository](https://gforge6.eufus.eu/gf/project/keplerworkflows/scmsvn/?action=browse&path=%2Ftrunk%2F). The workflow_matlab folder might still have to be removed.

**Comment by olaszsoma** [comment]
Discussed with Matyi, workflow-matlab is not needed.

**Comment by olaszsoma** [comment]
Workflows moved, folders removed. The issue can be closed.
