### ISSUE TITLE
Issue compiling the code at JET (older g++ compiler)

### ISSUE THREAD

**Issue by olivhoenen** [gergopokol/Runafluid#56]
The following error was raised by Dmitriy when attempting to build the last ETS release there:
`*** Compiler set to ITM *** 
g++ -pthread -g -fPIC  -pthread -I/common/ETS/switm/lib/itmconstants/1.4/include -I/common/ETS/switm/ual/4.10b.10_R2.3.5/include -I/usr/local/depot/blitz-0.10/include -I/common/ETS/switm/lib/hdf5/1.8.10/include     -DITM_CONSTANTS -I/common/ETS/switm/lib/xmllib/R3.4/4.10b/include/   -I/common/ETS/switm/lib/xmllib/R3.4/4.10b/include/amd64_intel_18 -I/usr/include/libxml2 -lTreeShr -lTdiShr -lXTreeShr   -c -o runafluid.o runafluid.cpp
runafluid.cpp: In function ‘void fire(ItmNs::Itm::coreprof&, ItmNs::Itm::coreimpur&, ItmNs::Itm::equilibrium&, ItmNs::Itm::distribution&, ItmNs::Itm::distribution&, double&, int&, int&, int&, ItmNs::codeparam_t&)’:
runafluid.cpp:207:57: error: variable-sized object ‘dataset_name_list’ may not be initialized
     "electric_field_vs_critical_field", "critical_field"};
                                                         ^
make: *** [runafluid.o] Error 1`

Declaring `dataset_name_length` as `const` or using a `new string[]` construct should solve the issue.

(https://github.com/osrep/Runafluid/blob/49a2c9fe9be70e1f1703088d34405ff5a322db28/runafluid.cpp#L202)

**Comment by olaszsoma** [comment]
Thanks, I will have a look into it.

**Comment by olaszsoma** [comment]
Bugfix committed, testing needed.

**Comment by olivhoenen** [comment]
Compilation worked at JET (Dmitriy is now testing the actor, but at least this one issue is solved).
