### ISSUE TITLE
Put check on availability of HDF5_BASE variable

### ISSUE THREAD

**Issue by olaszsoma** [gergopokol/Runafluid#64]
The location of the output hdf5 file depends on the HDF5_BASE variable. If this does not exist, Runafluid tries to create the file in the root, but the initialization is unsuccessful, as there is no permission to write there. It might be useful to implement a check if the variable exists (the hdf5_base input variable is empty) and if not give a warning and maybe abort the hdf5 writing (or use a hard coded location instead.)

**Comment by gergopokol** [comment]
Yep, this is important! I would go for giving a warning, and writing into the user home (~) if no appropriate system variable is found.

**Comment by olaszsoma** [comment]
I am not sure how the user home location can be given to the code. It should be added similarly to the HDF5_BASE variable, but how to decide in the workflow, if the needed location is present is a question.

**Comment by olaszsoma** [comment]
Check implemented, if hdf5_base is not defined, the array given to Runafluid will have size 0. If this is the case, the hdf5 file is not written, and a warning will be written to the Kepler log.
It would probably be better to check if hdf5_base is defined in the workflow, and if not add a different route to the hdf5_base input parameter of the Runafluid code.

**Comment by olaszsoma** [comment]
If HDF5_BASE is unavailable, the following approach may be used:

#include <unistd.h>
#include <sys/types.h>
#include <pwd.h>

const char *homedir;

if ((homedir = getenv("HOME")) == NULL) {
    homedir = getpwuid(getuid())->pw_dir;
}

**Comment by olaszsoma** [comment]
I have tried to get HDF5_BASE using the same method, but if the variable is undefined, Kepler crashes. It might be beneficial to get this variable in Kepler because if it is undefined, the input to Runafluid will be null, but the code would still run.

**Comment by olaszsoma** [comment]
Check added, tested.
