### ISSUE TITLE
Remove obsolete functions

### ISSUE THREAD

**Issue by olaszsoma** [gergopokol/Runafluid#74]
An [obsolete function](https://github.com/osrep/Runafluid/blob/development/codeparams.cpp#L59) for simulating codeparams is still included in the codeparams.cpp file. This is not used and should be removed.

**Comment by pordaniel01** [comment]
The functions `get_digit` and `bool_switch` seem to be obsolete. Also sthe function `sign` and `binary_search` and `interpolate` seems to be code duplications as they both appear the same way in ids_utils.cpp and cpo_utils.cpp.
