### ISSUE TITLE
Duplicate Ids_to_profile functions

### ISSUE THREAD

**Issue by olaszsoma** [gergopokol/Runafluid#91]
There are two separate ids_to_profile functions in the ids_utils.cpp file (similarly in cpo_utils.cpp). The [first function](https://github.com/osrep/Runafluid/blob/kepler_fix/src/ids_utils.cpp#L128) with fewer input parameters might not be used at all. This should be checked and removed if this is the case.

**Comment by pordaniel01** [comment]
Runafluid compiles without duplicate of function, however it should be tested in Kepler aswell.

**Comment by olaszsoma** [comment]
Functions have been removed. They were used in the Efield edit actor, which was already removed.
